{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "autoscaling/v1",
            "kind": "HorizontalPodAutoscaler",
            "metadata": {
                "name": "ecsdemo-nodejs",
                "namespace": "ecsdemo-nodejs"
            },
            "spec": {
                "maxReplicas": 10,
                "minReplicas": 2,
                "scaleTargetRef": {
                    "apiVersion": "apps/v1",
                    "kind": "Deployment",
                    "name": "ecsdemo-nodejs"
                },
                "targetCPUUtilizationPercentage": 40
            }
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}
